version: "3.8"
services:
  postgres-docker:
    container_name: postgres-docker
    image: postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  mongodb-docker:
    container_name: mongodb-docker
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge