spring:
  cloud:
    gateway:
      routes:
        - id: user-service-register-route
          uri: lb://user-service
          predicates:
            - Path=/register/**

        - id: user-service-login-route
          uri: lb://user-service
          predicates:
            - Path=/login/**

        - id: user-service-validate-route
          uri: lb://user-service
          predicates:
            - Path=/validate/**

        - id: wallet-service-add-money-route
          uri: lb://wallet-service
          predicates:
            - Path=/addMoneyToWallet/**
          filters:
            - AuthenticationFilter

        - id: wallet-service-get-balance-route
          uri: lb://wallet-service
          predicates:
            - Path=/getWalletBalance/**
          filters:
            - AuthenticationFilter

        - id: wallet-service-getWalletTxs-route
          uri: lb://wallet-service
          predicates:
            - Path=/getWalletTransactions/**
          filters:
            - AuthenticationFilter

        - id: stock-service-createStock-route
          uri: lb://stock-service
          predicates:
            - Path=/createStock/**
          filters:
            - AuthenticationFilter


        - id: stock-service-placeStockOrder-route
          uri: lb://stock-service
          predicates:
            - Path=/placeStockOrder/**
          filters:
            - AuthenticationFilter

        - id: stock-service-getStockTxs-route
          uri: lb://stock-service
          predicates:
            - Path=/getStockTransactions/**
          filters:
            - AuthenticationFilter

        - id: stock-service-getStockPortfolio-route
          uri: lb://stock-service
          predicates:
            - Path=/getStockPortfolio/**
          filters:
            - AuthenticationFilter

        - id: stock-service-addStockToUser-route
          uri: lb://stock-service
          predicates:
            - Path=/addStockToUser/**
          filters:
            - AuthenticationFilter


        - id: stock-service-getStockPrices-route
          uri: lb://stock-service
          predicates:
            - Path=/getStockPrices/**
          filters:
            - AuthenticationFilter

        - id: stock-service-cancelOrder-route
          uri: lb://stock-service
          predicates:
            - Path=/cancelStockTransaction/**
          filters:
            - AuthenticationFilter

